create table if not exists public.content_export_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  market_id text,
  selected_format text,
  selected_range text,
  source text,
  created_at timestamptz not null default now(),
  constraint content_export_events_event_name_check
    check (
      event_name in (
        'share_card_open',
        'share_card_download',
        'share_text_copy',
        'share_card_format_select'
      )
    ),
  constraint content_export_events_format_check
    check (selected_format is null or selected_format in ('square', 'story', 'landscape')),
  constraint content_export_events_range_check
    check (selected_range is null or selected_range in ('24h', '7d', '30d'))
);

alter table public.content_export_events
  drop constraint if exists content_export_events_event_name_check;

alter table public.content_export_events
  add constraint content_export_events_event_name_check
    check (
      event_name in (
        'share_card_open',
        'share_card_download',
        'share_text_copy',
        'share_card_format_select'
      )
    );

alter table public.content_export_events
  drop constraint if exists content_export_events_format_check;

alter table public.content_export_events
  add constraint content_export_events_format_check
    check (selected_format is null or selected_format in ('square', 'story', 'landscape'));

alter table public.content_export_events
  drop constraint if exists content_export_events_range_check;

alter table public.content_export_events
  add constraint content_export_events_range_check
    check (selected_range is null or selected_range in ('24h', '7d', '30d'));

create index if not exists content_export_events_created_at_idx
  on public.content_export_events (created_at desc);

create index if not exists content_export_events_market_created_at_idx
  on public.content_export_events (market_id, created_at desc);

create index if not exists content_export_events_event_name_created_at_idx
  on public.content_export_events (event_name, created_at desc);
