create table if not exists public.market_snapshots (
  id bigint generated by default as identity primary key,
  market_id text not null,
  market_question text not null,
  event_title text,
  category text,
  yes_probability numeric,
  movement numeric,
  volume numeric,
  liquidity numeric,
  source text,
  snapshot_hour timestamptz not null,
  captured_at timestamptz not null default now(),
  constraint market_snapshots_market_hour_unique unique (market_id, snapshot_hour),
  constraint market_snapshots_yes_probability_range
    check (yes_probability is null or (yes_probability >= 0 and yes_probability <= 100)),
  constraint market_snapshots_volume_non_negative
    check (volume is null or volume >= 0),
  constraint market_snapshots_liquidity_non_negative
    check (liquidity is null or liquidity >= 0)
);

create index if not exists market_snapshots_market_hour_idx
  on public.market_snapshots (market_id, snapshot_hour);

create index if not exists market_snapshots_captured_at_idx
  on public.market_snapshots (captured_at desc);
