create table if not exists public.start_funnel_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  source text,
  campaign text,
  content text,
  created_at timestamptz not null default now(),
  constraint start_funnel_events_event_name_check
    check (
      event_name in (
        'start_page_view',
        'start_lead_submit',
        'start_lead_success',
        'start_lead_existing',
        'start_live_board_click'
      )
    )
);

create index if not exists start_funnel_events_created_at_idx
  on public.start_funnel_events (created_at desc);

create index if not exists start_funnel_events_event_name_created_at_idx
  on public.start_funnel_events (event_name, created_at desc);
